name: Validate PR

on: 
 pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14.17.0
        uses: actions/setup-node@v1
        with:
         node-version: v14.17.0
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build --if-present
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build.zip
      
